#pragma config(Motor,  port2,            FRmotor,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            RRmotor,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            FLmotor,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            RLmotor,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// 'arcade'

task main {
    while(true){
        int  left_v = vexRT[Ch3];
        int  left_h = vexRT[Ch4];
        int right_v = -vexRT[Ch2];
        int right_h = -vexRT[Ch1];

        int fr = right_v - right_h;
        int rr = right_v + right_h;
        int fl = right_v + right_h;
        int rl = right_v - right_h;

        fr /= 2;
        rr /= 2;
        fl /= 2;
        rl /= 2;

        if(abs(fr) < 15) fr = 0;
        if(abs(rr) < 15) rr = 0;
        if(abs(fl) < 15) fl = 0;
        if(abs(rl) < 15) rl = 0;

        motor[FRmotor] = fr;
        motor[RRmotor] = rr;
        motor[FLmotor] = fl;
        motor[RLmotor] = rl;

        sleep(50);
    }
}

// 'tank'
/*

task main {
    while(true){
        int  left_v = vexRT[Ch3];
        int  left_h = vexRT[Ch4];
        int right_v = -vexRT[Ch2];
        int right_h = -vexRT[Ch1];

        left_h = -(right_h = (right_h - left_h) / 2);

        int fr = right_v - right_h;
        int rr = right_v + right_h;
        int fl = left_v + left_h;
        int rl = left_v - left_h;

        fr /= 2;
        rr /= 2;
        fl /= 2;
        rl /= 2;

        if(abs(fr) < 15) fr = 0;
        if(abs(rr) < 15) rr = 0;
        if(abs(fl) < 15) fl = 0;
        if(abs(rl) < 15) rl = 0;

        motor[FRmotor] = fr;
        motor[RRmotor] = rr;
        motor[FLmotor] = fl;
        motor[RLmotor] = rl;

        sleep(50);
    }
}
*/

